// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: talos/v1/talos.proto

package talosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TalosService_Append_FullMethodName       = "/talos.v1.TalosService/Append"
	TalosService_AppendStream_FullMethodName = "/talos.v1.TalosService/AppendStream"
	TalosService_Query_FullMethodName        = "/talos.v1.TalosService/Query"
	TalosService_Subscribe_FullMethodName    = "/talos.v1.TalosService/Subscribe"
)

// TalosServiceClient is the client API for TalosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TalosService is the ingest + query surface of the audit/event-stream
// service. Writes are append-only; there is no update or delete RPC.
type TalosServiceClient interface {
	// Append records a single audit event and returns its server-assigned id.
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// AppendStream records a batch of audit events from a client stream and
	// returns how many were persisted.
	AppendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendStreamRequest, AppendStreamResponse], error)
	// Query returns audit events matching the given filter, newest first.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Subscribe streams matching audit events. When replay_from is set the
	// server first replays matching history (oldest first) and then continues
	// with live events as they are appended, until the client disconnects.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
}

type talosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTalosServiceClient(cc grpc.ClientConnInterface) TalosServiceClient {
	return &talosServiceClient{cc}
}

func (c *talosServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, TalosService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talosServiceClient) AppendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AppendStreamRequest, AppendStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TalosService_ServiceDesc.Streams[0], TalosService_AppendStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendStreamRequest, AppendStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TalosService_AppendStreamClient = grpc.ClientStreamingClient[AppendStreamRequest, AppendStreamResponse]

func (c *talosServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TalosService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talosServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TalosService_ServiceDesc.Streams[1], TalosService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TalosService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

// TalosServiceServer is the server API for TalosService service.
// All implementations should embed UnimplementedTalosServiceServer
// for forward compatibility.
//
// TalosService is the ingest + query surface of the audit/event-stream
// service. Writes are append-only; there is no update or delete RPC.
type TalosServiceServer interface {
	// Append records a single audit event and returns its server-assigned id.
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// AppendStream records a batch of audit events from a client stream and
	// returns how many were persisted.
	AppendStream(grpc.ClientStreamingServer[AppendStreamRequest, AppendStreamResponse]) error
	// Query returns audit events matching the given filter, newest first.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Subscribe streams matching audit events. When replay_from is set the
	// server first replays matching history (oldest first) and then continues
	// with live events as they are appended, until the client disconnects.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
}

// UnimplementedTalosServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTalosServiceServer struct{}

func (UnimplementedTalosServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedTalosServiceServer) AppendStream(grpc.ClientStreamingServer[AppendStreamRequest, AppendStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method AppendStream not implemented")
}
func (UnimplementedTalosServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedTalosServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTalosServiceServer) testEmbeddedByValue() {}

// UnsafeTalosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TalosServiceServer will
// result in compilation errors.
type UnsafeTalosServiceServer interface {
	mustEmbedUnimplementedTalosServiceServer()
}

func RegisterTalosServiceServer(s grpc.ServiceRegistrar, srv TalosServiceServer) {
	// If the following call panics, it indicates UnimplementedTalosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TalosService_ServiceDesc, srv)
}

func _TalosService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalosServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalosService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalosServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalosService_AppendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TalosServiceServer).AppendStream(&grpc.GenericServerStream[AppendStreamRequest, AppendStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TalosService_AppendStreamServer = grpc.ClientStreamingServer[AppendStreamRequest, AppendStreamResponse]

func _TalosService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalosServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TalosService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalosServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalosService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TalosServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TalosService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

// TalosService_ServiceDesc is the grpc.ServiceDesc for TalosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TalosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talos.v1.TalosService",
	HandlerType: (*TalosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _TalosService_Append_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _TalosService_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AppendStream",
			Handler:       _TalosService_AppendStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _TalosService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "talos/v1/talos.proto",
}
