// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talos/v1/talos.proto

package talosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditEvent is one immutable record in the stream.
type AuditEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the server-assigned UUID of the event.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// timestamp is when the event occurred (server-defaulted when unset).
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// realm_id is the optional tenant the event belongs to.
	RealmId string `protobuf:"bytes,3,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// actor_id identifies who performed the action.
	ActorId string `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// actor_type classifies the actor (e.g. user, service, system).
	ActorType string `protobuf:"bytes,5,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	// resource_type is the kind of resource the action targeted.
	ResourceType string `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// resource_id is the id of the resource the action targeted.
	ResourceId string `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// action is the verb describing what happened (required).
	Action string `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	// summary is a short human-readable description of the event.
	Summary string `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	// changes is a structured before/after diff of the resource.
	Changes *structpb.Struct `protobuf:"bytes,10,opt,name=changes,proto3" json:"changes,omitempty"`
	// metadata is free-form structured context attached by the emitter.
	Metadata *structpb.Struct `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// ip is the source IP address associated with the action.
	Ip string `protobuf:"bytes,12,opt,name=ip,proto3" json:"ip,omitempty"`
	// request_id correlates the event with an upstream request.
	RequestId     string `protobuf:"bytes,13,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_talos_v1_talos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditEvent) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AuditEvent) GetChanges() *structpb.Struct {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *AuditEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// AppendRequest carries one event to record. id and timestamp are
// server-assigned when omitted.
type AppendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event is the audit event to record.
	Event         *AuditEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_talos_v1_talos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{1}
}

func (x *AppendRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// AppendResponse returns the id assigned to the recorded event.
type AppendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the server-assigned UUID of the recorded event.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_talos_v1_talos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{2}
}

func (x *AppendResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// AppendStreamRequest carries one event in an append stream. id and
// timestamp are server-assigned when omitted.
type AppendStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event is the audit event to record.
	Event         *AuditEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendStreamRequest) Reset() {
	*x = AppendStreamRequest{}
	mi := &file_talos_v1_talos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendStreamRequest) ProtoMessage() {}

func (x *AppendStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendStreamRequest.ProtoReflect.Descriptor instead.
func (*AppendStreamRequest) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{3}
}

func (x *AppendStreamRequest) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// AppendStreamResponse summarises a completed append stream.
type AppendStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// count is the number of events persisted by the stream.
	Count         uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendStreamResponse) Reset() {
	*x = AppendStreamResponse{}
	mi := &file_talos_v1_talos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendStreamResponse) ProtoMessage() {}

func (x *AppendStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendStreamResponse.ProtoReflect.Descriptor instead.
func (*AppendStreamResponse) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{4}
}

func (x *AppendStreamResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// QueryRequest filters the event stream. All fields are optional; empty
// fields are not constrained.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// actor_id filters to events performed by this actor.
	ActorId string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// resource_type filters to events targeting this resource kind.
	ResourceType string `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// resource_id filters to events targeting this resource id.
	ResourceId string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// action filters to events with this action verb.
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// from bounds the result set to events at or after this time.
	From *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	// to bounds the result set to events at or before this time.
	To *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	// limit caps the number of returned events.
	Limit         uint32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_talos_v1_talos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *QueryRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *QueryRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *QueryRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *QueryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *QueryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *QueryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// QueryResponse carries the matched events.
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// events are the matched audit events, newest first.
	Events []*AuditEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// total_count is the number of events matching the filter.
	TotalCount    uint32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_talos_v1_talos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// SubscribeRequest filters the live stream. All filter fields are optional;
// empty fields are not constrained. When replay_from is set, matching history
// from that time is replayed (oldest first) before the live tail begins.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// actor_id filters to events performed by this actor.
	ActorId string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// resource_type filters to events targeting this resource kind.
	ResourceType string `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// resource_id filters to events targeting this resource id.
	ResourceId string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// action filters to events with this action verb.
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// replay_from, when set, replays matching history at or after this time
	// before switching to the live tail.
	ReplayFrom *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=replay_from,json=replayFrom,proto3" json:"replay_from,omitempty"`
	// replay_limit caps the number of replayed history events.
	ReplayLimit   uint32 `protobuf:"varint,6,opt,name=replay_limit,json=replayLimit,proto3" json:"replay_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_talos_v1_talos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *SubscribeRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *SubscribeRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SubscribeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SubscribeRequest) GetReplayFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ReplayFrom
	}
	return nil
}

func (x *SubscribeRequest) GetReplayLimit() uint32 {
	if x != nil {
		return x.ReplayLimit
	}
	return 0
}

// SubscribeResponse carries one streamed audit event.
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event is the streamed audit event (replayed or live).
	Event         *AuditEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_talos_v1_talos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talos_v1_talos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_talos_v1_talos_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeResponse) GetEvent() *AuditEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_talos_v1_talos_proto protoreflect.FileDescriptor

const file_talos_v1_talos_proto_rawDesc = "" +
	"\n" +
	"\x14talos/v1/talos.proto\x12\btalos.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x03\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\brealm_id\x18\x03 \x01(\tR\arealmId\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x05 \x01(\tR\tactorType\x12#\n" +
	"\rresource_type\x18\x06 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x121\n" +
	"\achanges\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\achanges\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x0e\n" +
	"\x02ip\x18\f \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"request_id\x18\r \x01(\tR\trequestId\";\n" +
	"\rAppendRequest\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.talos.v1.AuditEventR\x05event\" \n" +
	"\x0eAppendResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x13AppendStreamRequest\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.talos.v1.AuditEventR\x05event\",\n" +
	"\x14AppendStreamResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"\xf9\x01\n" +
	"\fQueryRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12.\n" +
	"\x04from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\a \x01(\rR\x05limit\"^\n" +
	"\rQueryResponse\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.talos.v1.AuditEventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"\xeb\x01\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12;\n" +
	"\vreplay_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"replayFrom\x12!\n" +
	"\freplay_limit\x18\x06 \x01(\rR\vreplayLimit\"?\n" +
	"\x11SubscribeResponse\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.talos.v1.AuditEventR\x05event2\x9e\x02\n" +
	"\fTalosService\x12;\n" +
	"\x06Append\x12\x17.talos.v1.AppendRequest\x1a\x18.talos.v1.AppendResponse\x12O\n" +
	"\fAppendStream\x12\x1d.talos.v1.AppendStreamRequest\x1a\x1e.talos.v1.AppendStreamResponse(\x01\x128\n" +
	"\x05Query\x12\x16.talos.v1.QueryRequest\x1a\x17.talos.v1.QueryResponse\x12F\n" +
	"\tSubscribe\x12\x1a.talos.v1.SubscribeRequest\x1a\x1b.talos.v1.SubscribeResponse0\x01B\x98\x01\n" +
	"\fcom.talos.v1B\n" +
	"TalosProtoP\x01Z;github.com/fromforgesoftware/talos/pkg/api/talos/v1;talosv1\xa2\x02\x03TXX\xaa\x02\bTalos.V1\xca\x02\bTalos\\V1\xe2\x02\x14Talos\\V1\\GPBMetadata\xea\x02\tTalos::V1b\x06proto3"

var (
	file_talos_v1_talos_proto_rawDescOnce sync.Once
	file_talos_v1_talos_proto_rawDescData []byte
)

func file_talos_v1_talos_proto_rawDescGZIP() []byte {
	file_talos_v1_talos_proto_rawDescOnce.Do(func() {
		file_talos_v1_talos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talos_v1_talos_proto_rawDesc), len(file_talos_v1_talos_proto_rawDesc)))
	})
	return file_talos_v1_talos_proto_rawDescData
}

var file_talos_v1_talos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_talos_v1_talos_proto_goTypes = []any{
	(*AuditEvent)(nil),            // 0: talos.v1.AuditEvent
	(*AppendRequest)(nil),         // 1: talos.v1.AppendRequest
	(*AppendResponse)(nil),        // 2: talos.v1.AppendResponse
	(*AppendStreamRequest)(nil),   // 3: talos.v1.AppendStreamRequest
	(*AppendStreamResponse)(nil),  // 4: talos.v1.AppendStreamResponse
	(*QueryRequest)(nil),          // 5: talos.v1.QueryRequest
	(*QueryResponse)(nil),         // 6: talos.v1.QueryResponse
	(*SubscribeRequest)(nil),      // 7: talos.v1.SubscribeRequest
	(*SubscribeResponse)(nil),     // 8: talos.v1.SubscribeResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 10: google.protobuf.Struct
}
var file_talos_v1_talos_proto_depIdxs = []int32{
	9,  // 0: talos.v1.AuditEvent.timestamp:type_name -> google.protobuf.Timestamp
	10, // 1: talos.v1.AuditEvent.changes:type_name -> google.protobuf.Struct
	10, // 2: talos.v1.AuditEvent.metadata:type_name -> google.protobuf.Struct
	0,  // 3: talos.v1.AppendRequest.event:type_name -> talos.v1.AuditEvent
	0,  // 4: talos.v1.AppendStreamRequest.event:type_name -> talos.v1.AuditEvent
	9,  // 5: talos.v1.QueryRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 6: talos.v1.QueryRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 7: talos.v1.QueryResponse.events:type_name -> talos.v1.AuditEvent
	9,  // 8: talos.v1.SubscribeRequest.replay_from:type_name -> google.protobuf.Timestamp
	0,  // 9: talos.v1.SubscribeResponse.event:type_name -> talos.v1.AuditEvent
	1,  // 10: talos.v1.TalosService.Append:input_type -> talos.v1.AppendRequest
	3,  // 11: talos.v1.TalosService.AppendStream:input_type -> talos.v1.AppendStreamRequest
	5,  // 12: talos.v1.TalosService.Query:input_type -> talos.v1.QueryRequest
	7,  // 13: talos.v1.TalosService.Subscribe:input_type -> talos.v1.SubscribeRequest
	2,  // 14: talos.v1.TalosService.Append:output_type -> talos.v1.AppendResponse
	4,  // 15: talos.v1.TalosService.AppendStream:output_type -> talos.v1.AppendStreamResponse
	6,  // 16: talos.v1.TalosService.Query:output_type -> talos.v1.QueryResponse
	8,  // 17: talos.v1.TalosService.Subscribe:output_type -> talos.v1.SubscribeResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_talos_v1_talos_proto_init() }
func file_talos_v1_talos_proto_init() {
	if File_talos_v1_talos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talos_v1_talos_proto_rawDesc), len(file_talos_v1_talos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talos_v1_talos_proto_goTypes,
		DependencyIndexes: file_talos_v1_talos_proto_depIdxs,
		MessageInfos:      file_talos_v1_talos_proto_msgTypes,
	}.Build()
	File_talos_v1_talos_proto = out.File
	file_talos_v1_talos_proto_goTypes = nil
	file_talos_v1_talos_proto_depIdxs = nil
}
