// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/talos/internal/app"

	domain "github.com/fromforgesoftware/talos/internal/domain"

	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// AuditEventUsecase is an autogenerated mock type for the AuditEventUsecase type
type AuditEventUsecase struct {
	mock.Mock
}

type AuditEventUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEventUsecase) EXPECT() *AuditEventUsecase_Expecter {
	return &AuditEventUsecase_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, event
func (_m *AuditEventUsecase) Append(ctx context.Context, event domain.AuditEvent) (domain.AuditEvent, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 domain.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuditEvent) (domain.AuditEvent, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuditEvent) domain.AuditEvent); ok {
		r0 = rf(ctx, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuditEvent) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventUsecase_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type AuditEventUsecase_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AuditEvent
func (_e *AuditEventUsecase_Expecter) Append(ctx interface{}, event interface{}) *AuditEventUsecase_Append_Call {
	return &AuditEventUsecase_Append_Call{Call: _e.mock.On("Append", ctx, event)}
}

func (_c *AuditEventUsecase_Append_Call) Run(run func(ctx context.Context, event domain.AuditEvent)) *AuditEventUsecase_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AuditEvent))
	})
	return _c
}

func (_c *AuditEventUsecase_Append_Call) Return(_a0 domain.AuditEvent, _a1 error) *AuditEventUsecase_Append_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventUsecase_Append_Call) RunAndReturn(run func(context.Context, domain.AuditEvent) (domain.AuditEvent, error)) *AuditEventUsecase_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *AuditEventUsecase) Get(ctx context.Context, opts ...search.Option) (domain.AuditEvent, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.AuditEvent, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.AuditEvent); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AuditEventUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *AuditEventUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *AuditEventUsecase_Get_Call {
	return &AuditEventUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AuditEventUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *AuditEventUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AuditEventUsecase_Get_Call) Return(_a0 domain.AuditEvent, _a1 error) *AuditEventUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.AuditEvent, error)) *AuditEventUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *AuditEventUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.AuditEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.AuditEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.AuditEvent], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.AuditEvent]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.AuditEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AuditEventUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *AuditEventUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *AuditEventUsecase_List_Call {
	return &AuditEventUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AuditEventUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *AuditEventUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AuditEventUsecase_List_Call) Return(_a0 resource.ListResponse[domain.AuditEvent], _a1 error) *AuditEventUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.AuditEvent], error)) *AuditEventUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, f
func (_m *AuditEventUsecase) Query(ctx context.Context, f app.AuditEventFilter) (resource.ListResponse[domain.AuditEvent], error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 resource.ListResponse[domain.AuditEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, app.AuditEventFilter) (resource.ListResponse[domain.AuditEvent], error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, app.AuditEventFilter) resource.ListResponse[domain.AuditEvent]); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.AuditEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, app.AuditEventFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventUsecase_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type AuditEventUsecase_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - f app.AuditEventFilter
func (_e *AuditEventUsecase_Expecter) Query(ctx interface{}, f interface{}) *AuditEventUsecase_Query_Call {
	return &AuditEventUsecase_Query_Call{Call: _e.mock.On("Query", ctx, f)}
}

func (_c *AuditEventUsecase_Query_Call) Run(run func(ctx context.Context, f app.AuditEventFilter)) *AuditEventUsecase_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(app.AuditEventFilter))
	})
	return _c
}

func (_c *AuditEventUsecase_Query_Call) Return(_a0 resource.ListResponse[domain.AuditEvent], _a1 error) *AuditEventUsecase_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventUsecase_Query_Call) RunAndReturn(run func(context.Context, app.AuditEventFilter) (resource.ListResponse[domain.AuditEvent], error)) *AuditEventUsecase_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: f
func (_m *AuditEventUsecase) Subscribe(f app.AuditEventFilter) (*app.Subscription, error) {
	ret := _m.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 *app.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(app.AuditEventFilter) (*app.Subscription, error)); ok {
		return rf(f)
	}
	if rf, ok := ret.Get(0).(func(app.AuditEventFilter) *app.Subscription); ok {
		r0 = rf(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(app.AuditEventFilter) error); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventUsecase_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type AuditEventUsecase_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - f app.AuditEventFilter
func (_e *AuditEventUsecase_Expecter) Subscribe(f interface{}) *AuditEventUsecase_Subscribe_Call {
	return &AuditEventUsecase_Subscribe_Call{Call: _e.mock.On("Subscribe", f)}
}

func (_c *AuditEventUsecase_Subscribe_Call) Run(run func(f app.AuditEventFilter)) *AuditEventUsecase_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(app.AuditEventFilter))
	})
	return _c
}

func (_c *AuditEventUsecase_Subscribe_Call) Return(_a0 *app.Subscription, _a1 error) *AuditEventUsecase_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventUsecase_Subscribe_Call) RunAndReturn(run func(app.AuditEventFilter) (*app.Subscription, error)) *AuditEventUsecase_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditEventUsecase creates a new instance of AuditEventUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventUsecase {
	mock := &AuditEventUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
