// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	app "github.com/fromforgesoftware/talos/internal/app"

	domain "github.com/fromforgesoftware/talos/internal/domain"

	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// AuditEventRepository is an autogenerated mock type for the AuditEventRepository type
type AuditEventRepository struct {
	mock.Mock
}

type AuditEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEventRepository) EXPECT() *AuditEventRepository_Expecter {
	return &AuditEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *AuditEventRepository) Create(_a0 context.Context, _a1 domain.AuditEvent) (domain.AuditEvent, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuditEvent) (domain.AuditEvent, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuditEvent) domain.AuditEvent); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuditEvent) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuditEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.AuditEvent
func (_e *AuditEventRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *AuditEventRepository_Create_Call {
	return &AuditEventRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *AuditEventRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.AuditEvent)) *AuditEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AuditEvent))
	})
	return _c
}

func (_c *AuditEventRepository_Create_Call) Return(_a0 domain.AuditEvent, _a1 error) *AuditEventRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventRepository_Create_Call) RunAndReturn(run func(context.Context, domain.AuditEvent) (domain.AuditEvent, error)) *AuditEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *AuditEventRepository) Get(ctx context.Context, opts ...search.Option) (domain.AuditEvent, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.AuditEvent, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.AuditEvent); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AuditEventRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *AuditEventRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *AuditEventRepository_Get_Call {
	return &AuditEventRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AuditEventRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *AuditEventRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AuditEventRepository_Get_Call) Return(_a0 domain.AuditEvent, _a1 error) *AuditEventRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.AuditEvent, error)) *AuditEventRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *AuditEventRepository) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.AuditEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.AuditEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.AuditEvent], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.AuditEvent]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.AuditEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AuditEventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *AuditEventRepository_Expecter) List(ctx interface{}, opts ...interface{}) *AuditEventRepository_List_Call {
	return &AuditEventRepository_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *AuditEventRepository_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *AuditEventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *AuditEventRepository_List_Call) Return(_a0 resource.ListResponse[domain.AuditEvent], _a1 error) *AuditEventRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventRepository_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.AuditEvent], error)) *AuditEventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, f
func (_m *AuditEventRepository) Query(ctx context.Context, f app.AuditEventFilter) (resource.ListResponse[domain.AuditEvent], error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 resource.ListResponse[domain.AuditEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, app.AuditEventFilter) (resource.ListResponse[domain.AuditEvent], error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, app.AuditEventFilter) resource.ListResponse[domain.AuditEvent]); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.AuditEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, app.AuditEventFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditEventRepository_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type AuditEventRepository_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - f app.AuditEventFilter
func (_e *AuditEventRepository_Expecter) Query(ctx interface{}, f interface{}) *AuditEventRepository_Query_Call {
	return &AuditEventRepository_Query_Call{Call: _e.mock.On("Query", ctx, f)}
}

func (_c *AuditEventRepository_Query_Call) Run(run func(ctx context.Context, f app.AuditEventFilter)) *AuditEventRepository_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(app.AuditEventFilter))
	})
	return _c
}

func (_c *AuditEventRepository_Query_Call) Return(_a0 resource.ListResponse[domain.AuditEvent], _a1 error) *AuditEventRepository_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuditEventRepository_Query_Call) RunAndReturn(run func(context.Context, app.AuditEventFilter) (resource.ListResponse[domain.AuditEvent], error)) *AuditEventRepository_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditEventRepository creates a new instance of AuditEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventRepository {
	mock := &AuditEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
