// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/talos/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Forwarder is an autogenerated mock type for the Forwarder type
type Forwarder struct {
	mock.Mock
}

type Forwarder_Expecter struct {
	mock *mock.Mock
}

func (_m *Forwarder) EXPECT() *Forwarder_Expecter {
	return &Forwarder_Expecter{mock: &_m.Mock}
}

// Forward provides a mock function with given fields: ctx, event
func (_m *Forwarder) Forward(ctx context.Context, event domain.AuditEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuditEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Forwarder_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type Forwarder_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AuditEvent
func (_e *Forwarder_Expecter) Forward(ctx interface{}, event interface{}) *Forwarder_Forward_Call {
	return &Forwarder_Forward_Call{Call: _e.mock.On("Forward", ctx, event)}
}

func (_c *Forwarder_Forward_Call) Run(run func(ctx context.Context, event domain.AuditEvent)) *Forwarder_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AuditEvent))
	})
	return _c
}

func (_c *Forwarder_Forward_Call) Return(_a0 error) *Forwarder_Forward_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Forwarder_Forward_Call) RunAndReturn(run func(context.Context, domain.AuditEvent) error) *Forwarder_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Forwarder) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Forwarder_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Forwarder_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Forwarder_Expecter) Name() *Forwarder_Name_Call {
	return &Forwarder_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Forwarder_Name_Call) Run(run func()) *Forwarder_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Forwarder_Name_Call) Return(_a0 string) *Forwarder_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Forwarder_Name_Call) RunAndReturn(run func() string) *Forwarder_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewForwarder creates a new instance of Forwarder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForwarder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Forwarder {
	mock := &Forwarder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
