// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// PartitionProvisioner is an autogenerated mock type for the PartitionProvisioner type
type PartitionProvisioner struct {
	mock.Mock
}

type PartitionProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *PartitionProvisioner) EXPECT() *PartitionProvisioner_Expecter {
	return &PartitionProvisioner_Expecter{mock: &_m.Mock}
}

// Provision provides a mock function with given fields: ctx, now
func (_m *PartitionProvisioner) Provision(ctx context.Context, now time.Time) (int, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for Provision")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartitionProvisioner_Provision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provision'
type PartitionProvisioner_Provision_Call struct {
	*mock.Call
}

// Provision is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *PartitionProvisioner_Expecter) Provision(ctx interface{}, now interface{}) *PartitionProvisioner_Provision_Call {
	return &PartitionProvisioner_Provision_Call{Call: _e.mock.On("Provision", ctx, now)}
}

func (_c *PartitionProvisioner_Provision_Call) Run(run func(ctx context.Context, now time.Time)) *PartitionProvisioner_Provision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *PartitionProvisioner_Provision_Call) Return(_a0 int, _a1 error) *PartitionProvisioner_Provision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartitionProvisioner_Provision_Call) RunAndReturn(run func(context.Context, time.Time) (int, error)) *PartitionProvisioner_Provision_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartitionProvisioner creates a new instance of PartitionProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartitionProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartitionProvisioner {
	mock := &PartitionProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
