// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PartitionStore is an autogenerated mock type for the PartitionStore type
type PartitionStore struct {
	mock.Mock
}

type PartitionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PartitionStore) EXPECT() *PartitionStore_Expecter {
	return &PartitionStore_Expecter{mock: &_m.Mock}
}

// DropPartition provides a mock function with given fields: ctx, name
func (_m *PartitionStore) DropPartition(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DropPartition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PartitionStore_DropPartition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropPartition'
type PartitionStore_DropPartition_Call struct {
	*mock.Call
}

// DropPartition is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *PartitionStore_Expecter) DropPartition(ctx interface{}, name interface{}) *PartitionStore_DropPartition_Call {
	return &PartitionStore_DropPartition_Call{Call: _e.mock.On("DropPartition", ctx, name)}
}

func (_c *PartitionStore_DropPartition_Call) Run(run func(ctx context.Context, name string)) *PartitionStore_DropPartition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PartitionStore_DropPartition_Call) Return(_a0 error) *PartitionStore_DropPartition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PartitionStore_DropPartition_Call) RunAndReturn(run func(context.Context, string) error) *PartitionStore_DropPartition_Call {
	_c.Call.Return(run)
	return _c
}

// ListMonthlyPartitions provides a mock function with given fields: ctx
func (_m *PartitionStore) ListMonthlyPartitions(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListMonthlyPartitions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartitionStore_ListMonthlyPartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMonthlyPartitions'
type PartitionStore_ListMonthlyPartitions_Call struct {
	*mock.Call
}

// ListMonthlyPartitions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PartitionStore_Expecter) ListMonthlyPartitions(ctx interface{}) *PartitionStore_ListMonthlyPartitions_Call {
	return &PartitionStore_ListMonthlyPartitions_Call{Call: _e.mock.On("ListMonthlyPartitions", ctx)}
}

func (_c *PartitionStore_ListMonthlyPartitions_Call) Run(run func(ctx context.Context)) *PartitionStore_ListMonthlyPartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PartitionStore_ListMonthlyPartitions_Call) Return(_a0 []string, _a1 error) *PartitionStore_ListMonthlyPartitions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartitionStore_ListMonthlyPartitions_Call) RunAndReturn(run func(context.Context) ([]string, error)) *PartitionStore_ListMonthlyPartitions_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartitionStore creates a new instance of PartitionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartitionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartitionStore {
	mock := &PartitionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
