// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// RetentionSweeper is an autogenerated mock type for the RetentionSweeper type
type RetentionSweeper struct {
	mock.Mock
}

type RetentionSweeper_Expecter struct {
	mock *mock.Mock
}

func (_m *RetentionSweeper) EXPECT() *RetentionSweeper_Expecter {
	return &RetentionSweeper_Expecter{mock: &_m.Mock}
}

// Sweep provides a mock function with given fields: ctx, before
func (_m *RetentionSweeper) Sweep(ctx context.Context, before time.Time) (int, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for Sweep")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetentionSweeper_Sweep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sweep'
type RetentionSweeper_Sweep_Call struct {
	*mock.Call
}

// Sweep is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *RetentionSweeper_Expecter) Sweep(ctx interface{}, before interface{}) *RetentionSweeper_Sweep_Call {
	return &RetentionSweeper_Sweep_Call{Call: _e.mock.On("Sweep", ctx, before)}
}

func (_c *RetentionSweeper_Sweep_Call) Run(run func(ctx context.Context, before time.Time)) *RetentionSweeper_Sweep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *RetentionSweeper_Sweep_Call) Return(_a0 int, _a1 error) *RetentionSweeper_Sweep_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RetentionSweeper_Sweep_Call) RunAndReturn(run func(context.Context, time.Time) (int, error)) *RetentionSweeper_Sweep_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetentionSweeper creates a new instance of RetentionSweeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetentionSweeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetentionSweeper {
	mock := &RetentionSweeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
